package main

import (
        "fmt"
        "github.com/stianeikeland/go-rpio"
        "github.com/tarm/serial"
        //"github.com/goburrow/serial"
        "time"
        "os"
        "log"
        "flag"
        "net"
        "strconv"
)
const (
        gwState = rpio.Pin(17)
        lan9514 = rpio.Pin(20)
        lan9512 = rpio.Pin(21)
        rs485A = rpio.Pin(22)
        rs485B = rpio.Pin(23)
        rs485C = rpio.Pin(24)
        wireless = rpio.Pin(25)
)

func pinset(){
        if err := rpio.Open(); err!= nil{
                fmt.Println(err)
                os.Exit(1)
                }
        gwState.Output()
        lan9514.Output()
        lan9512.Output()
        rs485A.Output()
        rs485B.Output()
        rs485C.Output()
        wireless.Output()
}
func pintoggle(){
        gwState.Toggle()
        lan9514.Toggle()
        lan9512.Toggle()
        rs485A.Toggle()
        rs485B.Toggle()
        rs485C.Toggle()
}
//func time12(){
        //time1 := time.NewTimer(time.Second *2)
        //time.Sleep(time.Second)
        //stop1 := time1.Stop()
//}
func LedToggle(){
        //t := time.NewTimer(time.Millisecond)

        for{    //GPIO LED Toggle
                pintoggle()
                time.Sleep(time.Second)
        }
        //t.Stop(time.Millisecond)
        //t.Reset(time.Millisecond)
}
